data = [
    {"name": "Instagram", "follower_count": 287, "description": "Social media", "country": "United States"},
    {"name": "Cristiano Ronaldo", "follower_count": 113, "description": "Footballer", "country": "Portugal"},
    {"name": "Lionel Messi", "follower_count": 119, "description": "Footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "follower_count": 375, "description": "Singer", "country": "United States"},
    {"name": "Kim Kardashian", "follower_count": 156, "description": "TV personality", "country": "United States"},
    {"name": "Khloe Kardashian", "follower_count": 197, "description": "TV personality", "country": "United States"},
    {"name": "National Geographic", "follower_count": 409, "description": "Magazine", "country": "United States"},
    {"name": "Gucci", "follower_count": 435, "description": "Luxury brand", "country": "Italy"},
    {"name": "Virat Kohli", "follower_count": 299, "description": "Cricketer", "country": "India"},
    {"name": "Gigi Hadid", "follower_count": 208, "description": "Model", "country": "United States"},
    {"name": "Louis Vuitton", "follower_count": 414, "description": "Luxury brand", "country": "France"},
    {"name": "Chanel", "follower_count": 340, "description": "Luxury brand", "country": "France"},
    {"name": "BBC Earth", "follower_count": 285, "description": "Media", "country": "United Kingdom"},
    {"name": "Lamborghini", "follower_count": 232, "description": "Car brand", "country": "Italy"},
    {"name": "NASA", "follower_count": 462, "description": "Space agency", "country": "United States"},
    {"name": "Rolex", "follower_count": 484, "description": "Watch brand", "country": "Switzerland"},
    {"name": "Red Bull", "follower_count": 304, "description": "Energy drink", "country": "Austria"},
    {"name": "Pepsi", "follower_count": 173, "description": "Beverage", "country": "United States"},
    {"name": "Coca-Cola", "follower_count": 478, "description": "Beverage", "country": "United States"},
    {"name": "Harley-Davidson", "follower_count": 125, "description": "Motorcycles", "country": "United States"},
    {"name": "Gal Gadot", "follower_count": 300, "description": "Actor", "country": "Israel"},
    {"name": "Huda Kattan", "follower_count": 263, "description": "Beauty mogul", "country": "United States"},
    {"name": "FC Barcelona", "follower_count": 307, "description": "Football club", "country": "Spain"},
    {"name": "Ferrari", "follower_count": 424, "description": "Car brand", "country": "Italy"},
    {"name": "Chris Hemsworth", "follower_count": 375, "description": "Actor", "country": "Australia"},
    {"name": "Katy Perry", "follower_count": 184, "description": "Singer", "country": "United States"},
    {"name": "Zendaya", "follower_count": 456, "description": "Actor", "country": "United States"},
    {"name": "Emma Watson", "follower_count": 320, "description": "Actor", "country": "United Kingdom"},
    {"name": "Shawn Mendes", "follower_count": 378, "description": "Singer", "country": "Canada"},
    {"name": "LeBron James", "follower_count": 485, "description": "Basketballer", "country": "United States"},
    {"name": "Miley Cyrus", "follower_count": 348, "description": "Singer", "country": "United States"},
    {"name": "Rihanna", "follower_count": 463, "description": "Singer", "country": "Barbados"},
    {"name": "Kendall Jenner", "follower_count": 498, "description": "Model", "country": "United States"},
    {"name": "Drake", "follower_count": 469, "description": "Rapper", "country": "Canada"},
    {"name": "Shakira", "follower_count": 223, "description": "Singer", "country": "Colombia"},
    {"name": "Ellen DeGeneres", "follower_count": 228, "description": "TV host", "country": "United States"},
    {"name": "Nike", "follower_count": 362, "description": "Sports brand", "country": "United States"},
    {"name": "Kylie Jenner", "follower_count": 191, "description": "Beauty mogul", "country": "United States"},
    {"name": "Porsche", "follower_count": 106, "description": "Car brand", "country": "Germany"},
    {"name": "Kevin Hart", "follower_count": 86, "description": "Comedian", "country": "United States"}
]
